months:
  2019-01: {}
  2019-02:
    Uni payments:
      total: 1900
      transactionList: [PAY UNIVERSITY OF AUCKLAND - STUDENT PAYMENTS ;075334DpsA2A
          UoA A2A 2487]
  2019-03:
    Liquor:
      total: 42
      transactionList: [CHEERS LIQUOR...]
transactionNameMap: {}
