months:
  2019-01:
    Income:
      total: 22776
      transactionList: []
  2019-02:
    Income:
      total: 182
      transactionList: []
    Uni payments:
      total: 18097
      transactionList: [PAY UNIVERSITY OF AUCKLAND - STUDENT PAYMENTS ;075334DpsA2A
          UoA A2A 2487, PAY UNIVERSITY OF AUCKLAND - STUDENT PAYMENTS ;075334DpsA2A
          UoA A2A 248706]
  2019-03:
    Food:
      total: 250
      transactionList: [COUNTDOWN AKL METRO AUCKLAND ;, 'POS W/D CHEERS LIQUOR-16:54
          ;']
    Income:
      total: 2671
      transactionList: []
    Phone:
      total: 20
      transactionList: [VODAFONE PREPAY VISA MCAUCKLAND ;]
  2019-04:
    Income:
      total: 18528
      transactionList: []
  2019-05:
    Income:
      total: 18871
      transactionList: []
    Tuition:
      total: 18252
      transactionList: [PAY UNIVERSITY OF AUCKLAND - STUDENT PAYMENTS ;084743DpsA2A
          UoA A2A 270461]
    frivolity:
      total: 250
      transactionList: ['POS W/D FAT CAMEL HOS-20:39 ;', 'POS W/D FAT CAMEL HOS-21:03
          ;', BARILLA DUMPLING AUCKLAND ;, BURGER FUEL PARNELL AUCKLAND ;, HA POKE
          AUCKLAND ;, 'POS W/D FAT CAMEL HOS-20:34 ;', 'POS W/D FAT CAMEL HOS-20:57
          ;', 'POS W/D SHADOWS BAR S-21:45 ;', JAPAN MART CITY CENTRALAUCKLAND ;,
        MUNCHY MART LIMITED AUCKLAND ;, FUREIN ASIAN AUCKLAND ;, THE WHITE LADY AUCKLAND
          ;, PAY Annie ;, 'POS W/D ZAM ZAM TRADI-13:25 ;', 'POS W/D TRIPLE 5 TRAD-13:22
          ;']
    groceries:
      total: 430
      transactionList: [COUNTDOWN AKL CENTRAL AUCKLAND ;, COUNTDOWN AKL METRO AUCKLAND
          ;, 'POS W/D TAI PING TRAD-13:59 ;', TWL 221 ATRIUM AUCKLAND ;]
    rent:
      total: 1800
      transactionList: [UOA ACCOMMODATION AUCKLAND ;]
    sth island:
      total: 300
      transactionList: [JETSTAR AUCKLAND ;]
    upkeep:
      total: 60
      transactionList: [VODAFONE PREPAY VISA MCAUCKLAND ;, PAY Samuel Fonacier ;,
        UNIVERSITY BOOK SHOP AUCKLAND ;]
  2019-06:
    Frivolity:
      total: 270
      transactionList: [BARILLA DUMPLING AUCKLAND ;, THE WHITE LADY AUCKLAND ;, THE
          SHELF AUCKLAND ;, SOUTHERN MAID DONUTS AUCKLAND ;, PAY Monica ;, MUNCHY
          MART LIMITED AUCKLAND ;, BURGER FUEL PARNELL AUCKLAND ;, FUTURE CLUB AUCKLAND
          ;, 'ATM W/D Victoria St W-01:19 ;', LIM 8885463345 CA ;, OLACABS RIDE PAYMENT
          AUCKLAND ;, AT HOP AUCKLAND HENDERSON ;, PAY Annie ;, 'POS W/D SOMEKIND
          LIMI-12:25 ;']
    Income:
      total: 442
      transactionList: []
    groceries:
      total: 340
      transactionList: [COUNTDOWN AKL METRO AUCKLAND ;]
    rent:
      total: 875
      transactionList: [UOA ACCOMMODATION AUCKLAND ;]
    trips:
      total: 585
      transactionList: [NPD GREEN ISLAND NPD GREEN ISLAND ;, FOUR SQUARE MACKENZIE
          TWIZEL ;, TWL 220 RICCARTON RICCARTON ;, FOUR SQUARE TE ANAU TE ANAU ;,
        'POS W/D DF SOUVENIRS -15:44 ;', PIG & WHISTLE QUEENSTOWN ;, KAWARAU JET LTD
          QUEENSTOWN ;, QUEENSTOWN AIRPORT QUEENSTOWN ;, SNAKE BITE BREWERY FRANZ
          JOSEF G ;, RELAY CHRISTCHURCH ;, MOBIL BULLS BULLS ;, GEOZONE AUCKLAND ;,
        KIWI FUELS LTD KIWI FUELS LTD ;, TWL 141 HAMILTON HAMILTON ;, NEW WORLD FOXTON
          FOXTON ;, 'POS W/D MASTER CHEF K-16:44 ;', CASH WITHDRAWAL ;, JUCY RENTALS
          NZ LIMITEDAUK ;]
    upkeep:
      total: 70
      transactionList: [VODAFONE PREPAY VISA MCAUCKLAND ;, 'POS W/D BARKERS GROOM-13:21
          ;']
    visa renewal:
      total: 35
      transactionList: [CAMPUS PHARMACY AUCKLAND ;, CAMPUS CARD OFFICE AUCKLAND ;,
        'TRANSACTION PRINTOUT FEE #38 9019 0725301 00 ;']
  2019-07:
    Groceries:
      total: 150
      transactionList: [COUNTDOWN AKL METRO AUCKLAND ;, COUNTDOWN AKL CENTRAL AUCKLAND
          ;]
    Income:
      total: 550
      transactionList: []
    Maint:
      total: 50
      transactionList: [PERSIA BARBER AUCKLAND ;, VODAFONE PREPAY VISA MCAUCKLAND
          ;]
    Out:
      total: 100
      transactionList: [PAY Annie ;, OLACABS RIDE PAYMENT AUCKLAND ;, DOMINO'S PIZZA
          - AUC AUCKLAND ;, 'POS W/D THE TANDOOR T-20:53 ;', BAR101 AUCKLAND ;, 'POS
          W/D MCDONALDS AIR-20:56 ;']
    Trips:
      total: 127
      transactionList: [Z MATAMATA Z MATAMATA ;, GULL KINGSLAND SPEEDLANE GULL KINGSLAN
          ;, COUNTDOWN TAURANGA TAURANGA ;, 'POS W/D The Warehouse-12:56 ;', AT HOP
          AUCKLAND HENDERSON ;]
transactionNameMap: {}
