class Events:
    set_config = 'set_config'
    transaction_drop_event = 'transaction_drop_event'
    remove_category = 'remove_category'
    remove_all_categories = 'remove_all_categories'
    update_category_total = 'update_category_total'
    update_category_title = 'update_category_title'
    update_total = 'update_total'
    add_category = 'add_category'
    metrics_close = 'metrics_close'